var inter=7e3,s=document.createElement("link");s.rel="stylesheet",s.href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css",document.head.appendChild(s),document.querySelector(".slideshow").innerHTML+=`
\t\t<div style="height:60px;display:flex;justify-content:center;align-items:center">
\t\t\t<i class="fa fa-arrow-left fa-2x left" aria-hidden="true" style="margin-right:20px"></i>
\t\t\t<div class="player">
\t\t\t\t<i class="fa fa-pause fa-2x pause" aria-hidden="true"></i>
\t\t\t\t<i class="fa fa-play fa-2x play" aria-hidden="true" style="display:none"></i>
\t\t\t</div>
\t\t\t<i class="fa fa-arrow-right fa-2x right" aria-hidden="true" style="margin-left:20px"></i>
\t\t</div>
\t`,document.querySelector(".pause").addEventListener("click",function(){clearInterval(window.SlideBot),document.querySelector(".pause").style.display="none",document.querySelector(".play").style.display="block"}),document.querySelector(".play").addEventListener("click",function(){document.querySelector(".pause").style.display="block",document.querySelector(".play").style.display="none",window.SlideBot=setInterval(()=>{var a=Array.from(document.querySelectorAll(".img-slide")),b=document.querySelector(".active"),c=a.indexOf(b)+1;c==a.length&&(c=0);b.className=b.className.replace(" active","");a[c].className+=" active"},inter)}),document.querySelector(".left").addEventListener("click",function(){var a=Array.from(document.querySelectorAll(".img-slide")),b=document.querySelector(".active"),c=a.indexOf(b)-1;0>c&&(c=a.length-1),console.log(c),b.className=b.className.replace(" active",""),a[c].className+=" active",inter=15e3,setTimeout(()=>{inter=7e3},14e3)}),document.querySelector(".right").addEventListener("click",function(){var a=Array.from(document.querySelectorAll(".img-slide")),b=document.querySelector(".active"),c=a.indexOf(b)+1;c==a.length&&(c=0),console.log(c),b.className=b.className.replace(" active",""),a[c].className+=" active",inter=15e3,setTimeout(()=>{inter=7e3},14e3)});var slides=Array.from(document.querySelectorAll(".img-slide"));slides.forEach((a,b)=>{0==b&&(a.className+=" active");a.style.backgroundImage='url("'+a.getAttribute("image-src")+'")'}),window.SlideBot=setInterval(()=>{var a=Array.from(document.querySelectorAll(".img-slide")),b=document.querySelector(".active"),c=a.indexOf(b)+1;c==a.length&&(c=0);b.className=b.className.replace(" active","");a[c].className+=" active"},inter);
